#!/usr/bin/env python3
"""Generate the checked-in function reference from functions.toml."""

from __future__ import annotations

import argparse
import sys
import tomllib
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "crates" / "jpx-core" / "functions.toml"
OUTPUT_DIR = ROOT / "docs" / "src" / "functions"

CATEGORIES = [
    ("standard", "Standard JMESPath", "Standard functions defined by the JMESPath specification."),
    ("string", "String", "Functions for transforming, inspecting, and formatting strings."),
    ("array", "Array", "Functions for transforming, grouping, and inspecting arrays."),
    ("object", "Object", "Functions for transforming, merging, and inspecting objects."),
    ("math", "Math", "Mathematical and statistical functions."),
    ("datetime", "Date/Time", "Functions for parsing, formatting, and calculating with dates and times."),
    ("duration", "Duration", "Functions for parsing, formatting, and calculating durations."),
    ("hash", "Hash", "Cryptographic and checksum hash functions."),
    ("encoding", "Encoding", "Encoding and decoding functions."),
    ("validation", "Validation", "Functions for validating common data formats."),
    ("expression", "Expression", "Higher-order functions that evaluate JMESPath expression references."),
    ("type", "Type", "Type conversion and inspection functions."),
    ("regex", "Regular Expression", "Regular-expression matching and transformation functions."),
    ("url", "URL", "Functions for parsing and constructing URLs and query strings."),
    ("semver", "Semantic Versioning", "Functions for inspecting and comparing semantic versions."),
    ("jsonpatch", "JSON Patch", "JSON Patch (RFC 6902) and JSON Merge Patch (RFC 7396) functions."),
    ("multimatch", "Multi-Match", "Functions for matching and replacing multiple patterns."),
    ("uuid", "UUID", "UUID generation functions."),
    ("ids", "ID Generation", "Functions for generating and inspecting identifiers."),
    ("rand", "Random", "Random number and sampling functions."),
    ("text", "Text", "Text analysis and natural-language utility functions."),
    ("language", "Language", "Language and writing-system detection functions."),
    ("fuzzy", "Fuzzy", "String similarity and fuzzy-matching functions."),
    ("discovery", "Discovery", "Functions for relevance-ranked discovery over collections."),
    ("phonetic", "Phonetic", "Phonetic encoding and comparison functions."),
    ("network", "Network", "IP address and CIDR utility functions."),
    ("geo", "Geolocation", "Geographic distance, bearing, and geohash functions."),
    ("path", "Path", "Portable file-path manipulation functions."),
    ("format", "Format", "CSV and TSV conversion functions."),
    ("color", "Color", "Color conversion and manipulation functions."),
    ("computing", "Computing", "Bitwise and low-level computing utility functions."),
    ("utility", "Utility", "General-purpose utility functions."),
    ("units", "Units", "Unit conversion functions."),
]


def escape_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def examples(function: dict) -> list[dict]:
    result: list[dict] = []
    if legacy := function.get("example"):
        result.append({"code": legacy})
    result.extend(function.get("examples", []))
    return result


def category_page(title: str, intro: str, functions: list[dict]) -> str:
    lines = [
        f"# {title} Functions",
        "",
        intro,
        "",
        "<!-- Generated by docs/generate_function_docs.py; do not edit directly. -->",
        "",
        "## Summary",
        "",
        "| Function | Signature | Description |",
        "|----------|-----------|-------------|",
    ]

    for function in functions:
        name = function["name"]
        lines.append(
            f"| [`{name}`](#{name}) | `{escape_cell(function['signature'])}` | "
            f"{escape_cell(function['description'])} |"
        )

    lines.extend(["", "## Functions", ""])
    for function in functions:
        for alias in function.get("aliases", []):
            lines.append(f'<a id="{alias}"></a>')
        lines.extend(
            [
                f"### {function['name']}",
                "",
                function["description"],
                "",
                f"**Signature:** `{function['signature']}`",
                "",
            ]
        )
        if aliases := function.get("aliases"):
            lines.extend([f"**Aliases:** {', '.join(f'`{alias}`' for alias in aliases)}", ""])
        if jep := function.get("jep"):
            lines.extend([f"**JEP:** {jep}", ""])
        function_examples = examples(function)
        if function_examples:
            lines.extend(["**Examples:**", "", "```text"])
            for example in function_examples:
                if description := example.get("description"):
                    lines.append(f"# {description}")
                lines.append(example["code"])
            lines.extend(["```", ""])

    return "\n".join(lines).rstrip() + "\n"


def overview_page(grouped: dict[str, list[dict]]) -> str:
    total = sum(len(functions) for functions in grouped.values())
    standard = len(grouped["standard"])
    extensions = total - standard
    lines = [
        "# Function Overview",
        "",
        f"jpx provides {total} functions: {standard} standard JMESPath functions and "
        f"{extensions} extensions organized into {len(CATEGORIES)} categories.",
        "",
        "<!-- Generated by docs/generate_function_docs.py; do not edit directly. -->",
        "",
        "## Discovering Functions",
        "",
        "```bash",
        "jpx --list-functions",
        "jpx --list-category string",
        "jpx --describe upper",
        "jpx --search 'date format'",
        "```",
        "",
        "## Categories",
        "",
        "| Category | Description | Count |",
        "|----------|-------------|------:|",
    ]
    for slug, title, intro in CATEGORIES:
        lines.append(f"| [{title}](./{slug}.md) | {intro} | {len(grouped[slug])} |")
    return "\n".join(lines) + "\n"


def render() -> dict[Path, str]:
    with REGISTRY.open("rb") as registry_file:
        functions = tomllib.load(registry_file)["functions"]

    grouped: dict[str, list[dict]] = defaultdict(list)
    for function in functions:
        grouped[function["category"]].append(function)
    for category_functions in grouped.values():
        category_functions.sort(key=lambda function: function["name"])

    expected_categories = {slug for slug, _, _ in CATEGORIES}
    actual_categories = set(grouped)
    if actual_categories != expected_categories:
        missing = sorted(actual_categories - expected_categories)
        removed = sorted(expected_categories - actual_categories)
        raise SystemExit(f"category metadata is stale; add={missing}, remove={removed}")

    rendered = {OUTPUT_DIR / "overview.md": overview_page(grouped)}
    for slug, title, intro in CATEGORIES:
        rendered[OUTPUT_DIR / f"{slug}.md"] = category_page(title, intro, grouped[slug])
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if checked-in documentation is stale"
    )
    args = parser.parse_args()

    stale: list[Path] = []
    for path, content in render().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT))
        else:
            path.write_text(content, encoding="utf-8")

    if stale:
        print("Function documentation is stale. Run docs/generate_function_docs.py:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
